### ISSUE TITLE
Package.json file is missing 

### ISSUE THREAD

**Issue by bayernmunich** [AndyLPK247/python-testing-101#1]
**Install fix-styles package task** is looking for package.json which is missing in source directory !!!!

**Comment by AndyLPK247** [comment]
This issue needs more information.
- What is "Install fix-styles package task"?
- How did you set up this project?
- Do you have any logs or screen shots?

**Comment by AndyLPK247** [comment]
@bayernmunich please reply

**Comment by AndyLPK247** [comment]
Did not mean to close... hit the wrong button...

**Comment by bayernmunich** [comment]
hi @AndyLPK247  thanks for the reply!!!!
http://www.colinsalmcorner.com/post/using-vsts-to-test-python-code-with-code-coverage i am following the above blog. If you see build definition in that there is task called **Install fix-styles package task** this task requires  package.json which is missing in the **root directory**!! please help me to fix this issue!!

**Comment by bayernmunich** [comment]
Here is the screenshot for the task and logs !!

![task](https://user-images.githubusercontent.com/28861133/37089566-fb3bf686-2226-11e8-8a01-ed30b741f0ad.png)

![logs](https://user-images.githubusercontent.com/28861133/37089409-78ddffae-2226-11e8-8067-c00628eacc01.png)

**Comment by AndyLPK247** [comment]
Hi @bayernmunich,

Thanks for the additional info. This is not an issue with the example project, but rather it is a setup issue on your side.

Question: why are you are trying to use NPM to install packages? This repository has a set of Python projects. There’s no JavaScript. To run the examples, simply install Python on your machine and use pip to install any required packages.

Please give that a try. I’m going to close this issue. 

Sincerely,
Andy
